### ISSUE TITLE
not connecting anymore

### ISSUE THREAD

**Issue by Head** [mappum/bitcoin-net#65]
See screenshot. After the latest npm install the bridge/everything is not working anymore:

![unbenannt](https://cloud.githubusercontent.com/assets/51700/18034915/4189d466-6d4a-11e6-9642-dc602504b047.PNG)

**Comment by mappum** [comment]
Hm, nothing there should have changed. Thanks for the heads up, I'll check it out.

**Comment by Head** [comment]
maybe it's the peer-exchange repo with v1.0.0?

**Comment by Head** [comment]
\npm\node_modules\webcoin-bridge\node_modules\bitcoin-net\lib\bridge.js:30
      return (_this2 = _this)._selectPeer.apply(_this2, arguments);
                                         ^

TypeError: Cannot read property 'apply' of undefined
    at Peer.selectPeer (\npm\node_modules\webcoin-bridge\node_modules\bitcoin-net\lib\bridge.js:30:42)
    at Peer._onGetPeer (\npm\node_modules\webcoin-bridge\node_modules\peer-exchange\lib\peer.js:268:8)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (\npm\node_modules\webcoin-bridge\node_modules\peer-exchange\lib\peer.js:92:36)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at readableAddChunk (\npm\node_modules\webcoin-bridge\node_modules\readable-stream\lib_stream_readable.js:198:18)
    at Readable.push (\npm\node_modules\webcoin-bridge\node_modules\readable-stream\lib_stream_readable.js:157:10)
    at Duplexify._forward (\npm\node_modules\webcoin-bridge\node_modules\duplexify\index.js:162:26)

**Comment by Head** [comment]
Yep, the peer-exchange@5.3 works. I have to install the bridge 1.3.0 with bitcoin-net 4.3.2 and delete the bitcoin-net folder in the bridge/nodue_modules. Then it works again.

It seems like your testnet webSeeds are all down too. They don't respond in http://websocket.org/echo.html

**Comment by mappum** [comment]
I think the Let's Encrypt certs expired, and that crashed them. I started rewriting `peer-exchange` yesterday to better handle relaying to TCP nodes, I expect to publish it today. I'll renew the certificates and put the webseeds back up.

Would you be interested in running a web seed? It would be nice to have the ownership of them less centralized. It only really needs bandwidth, it could run on a $5 VPS.

**Comment by mappum** [comment]
Oh, you said it is working with 0.5.3? Hm, I'm not sure how you can connect to the webseeds seeing as the certs have expired.

**Comment by Head** [comment]
5.3 with my local node.
I'm not sure. The crash above is also the local one, without a cert.
It's hard for me to debug what exactly happens because I'm new to nodejs. Worked 15 years with PHP...

I could setup one if I find a decent hoster for node. What exactly do they do? They bridge all traffic from the clients to the Bitcoin nodes? Or do the webclients connect to other clients?

**Comment by mappum** [comment]
Ah, I never looked at your crash stack trace, the problem is coming from some changes I made a while ago in `peer-exchange` which I'm unhappy with, hence the rewrite. Migrating to the new version once it's ready will fix this.

> Worked 15 years with PHP...

😮 Wow! I didn't even know PHP was 15 years old.
